//! Machine-wide guard rails.
//!
//! Two things live here. First, turning the global identity from a value into a
//! fuse: with no global `user.email` and `user.useConfigOnly` set, a repository
//! that was never bound refuses to commit instead of borrowing the identity of
//! whichever profile happens to be active. Second, a generated `includeIf`
//! region in `~/.gitconfig` so a fresh clone under a known root already knows
//! who it belongs to.
//!
//! The region is delimited the same way the SSH config region is, and anything
//! outside it is preserved byte for byte.

use crate::git;
use crate::hooks;
use crate::models::{
    GuardSettings, Platform, PlatformAccount, Profile, RepoBinding, RepoRoot, MANAGED_FOOTER,
    MANAGED_HEADER, PLATFORMS,
};
use crate::repos::allowed_emails;
use crate::ssh;
use serde::{Deserialize, Serialize};
use std::fs;
use std::path::PathBuf;

fn gitconfig_path() -> Result<PathBuf, String> {
    Ok(dirs::home_dir()
        .ok_or("Cannot find home directory")?
        .join(".gitconfig"))
}

fn identities_dir() -> Result<PathBuf, String> {
    let dir = dirs::data_dir()
        .ok_or("Cannot find data directory")?
        .join("git-account-manager")
        .join("identities");
    fs::create_dir_all(&dir).map_err(|e| e.to_string())?;
    Ok(dir)
}

fn identity_file(profile: &Profile, platform: Platform) -> Result<PathBuf, String> {
    Ok(identities_dir()?.join(format!(
        "{}-{}.gitconfig",
        profile.slug(),
        platform.as_str()
    )))
}

const BINDING_FILE_PREFIX: &str = "binding-";

/// One file per bound repository, carrying the addresses the guard accepts
/// there. Named by the path so a stale file is recognisable, plus a hash so
/// two paths that slug alike ("a-b" and "a/b") do not share one.
fn binding_file(binding: &RepoBinding) -> Result<PathBuf, String> {
    let path = binding.path.replace('\\', "/");
    let mut hash: u64 = 0xcbf2_9ce4_8422_2325;
    for byte in path.bytes() {
        hash ^= u64::from(byte);
        hash = hash.wrapping_mul(0x0100_0000_01b3);
    }
    let slug: String = crate::models::slugify(&path).chars().take(48).collect();
    Ok(identities_dir()?.join(format!(
        "{}{}-{:016x}.gitconfig",
        BINDING_FILE_PREFIX, slug, hash
    )))
}

fn allow_list_body(emails: &[String]) -> String {
    let mut body = String::from("[gam]\n");
    for email in emails {
        body.push_str(&format!("\tallowedEmail = {}\n", config_value(email)));
    }
    body
}

/// Renders a value the way `git config` will read it back.
///
/// Inside a config value a backslash escapes the following character and a
/// quote opens a quoted run, so a name holding either — `C:\Users`, a nickname
/// in quotes — written literally produces a file git parses into something
/// else, or refuses outright. Quoting the whole value and escaping those two is
/// what git's own writer does. A newline cannot appear in a value at all: it
/// would end the line and turn the remainder into a second key, so it goes.
fn config_value(raw: &str) -> String {
    let mut out = String::with_capacity(raw.len() + 2);
    out.push('"');
    for c in raw.chars() {
        match c {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' | '\r' => {}
            _ => out.push(c),
        }
    }
    out.push('"');
    out
}

fn posix(path: &std::path::Path) -> String {
    path.to_string_lossy().replace('\\', "/")
}

/// The whole content of one generated identity file: who the account is, and —
/// when it signs — which key signs for it. `gpg.format = ssh` has to travel with
/// `user.signingkey`, or git reads the path as a GPG key id and every commit in
/// the including repository fails.
fn identity_file_body(account: &PlatformAccount) -> String {
    let signing = match account.signing_key() {
        Some(key) => format!(
            "\tsigningkey = {}\n[gpg]\n\tformat = ssh\n[commit]\n\tgpgsign = true\n[tag]\n\tgpgsign = true\n",
            config_value(&key.replace('\\', "/"))
        ),
        None => String::new(),
    };
    // The account's own address is always allowed where its identity applies,
    // so a repository matched by remote alone is guarded too.
    format!(
        "# Generated by git-account-manager. Edits are overwritten.\n[user]\n\tname = {}\n\temail = {}\n{}{}",
        config_value(&account.git_name),
        config_value(&account.git_email),
        signing,
        allow_list_body(std::slice::from_ref(&account.git_email))
    )
}

/// Whose key a bare SSH host answers with; `profile` is `None` where nothing
/// does, so the page can say a `git@<host>:` remote is refused there.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SshHostOwner {
    pub host: String,
    pub profile: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GuardStatus {
    pub global_name: String,
    pub global_email: String,
    pub use_config_only: bool,
    pub includes_managed: bool,
    pub gitconfig_path: String,
    pub ssh_hosts: Vec<SshHostOwner>,
    /// What the global `core.hooksPath` points at, if anything.
    pub hooks_path: Option<String>,
    /// `global` when the dispatchers are in force, `foreign` when the path is
    /// somebody else's, `off` when nothing is set.
    pub hooks: String,
    pub ok: bool,
}

pub fn status(settings: &GuardSettings, profiles: &[Profile]) -> GuardStatus {
    let identity = git::get_global_identity().unwrap_or(git::GitIdentity {
        name: String::new(),
        email: String::new(),
    });
    let use_config_only = git::get_global_config("user.useConfigOnly")
        .map(|v| v == "true")
        .unwrap_or(false);
    let path = gitconfig_path().unwrap_or_default();
    let includes_managed = fs::read_to_string(&path)
        .map(|c| c.contains(MANAGED_HEADER))
        .unwrap_or(false);

    let identity_ok =
        !settings.unset_global_identity || (identity.email.is_empty() && use_config_only);
    let includes_ok = !settings.manage_gitconfig_includes || includes_managed;

    let hooks_status = hooks::status();
    let hooks_state = match (&hooks_status.hooks_path, hooks_status.ours) {
        (Some(_), true) => "global",
        (Some(_), false) => "foreign",
        (None, _) => "off",
    };
    let hooks_ok = !settings.guard_commits || hooks_state == "global";

    GuardStatus {
        global_name: identity.name,
        global_email: identity.email,
        use_config_only,
        includes_managed,
        gitconfig_path: posix(&path),
        ssh_hosts: ssh::bare_host_owners(profiles)
            .into_iter()
            .map(|(platform, owner)| SshHostOwner {
                host: platform.canonical_host().to_string(),
                profile: owner.map(|p| p.name.clone()),
            })
            .collect(),
        hooks_path: hooks_status.hooks_path,
        hooks: hooks_state.to_string(),
        ok: identity_ok && includes_ok && hooks_ok,
    }
}

/// Brings the machine in line with the settings.
///
/// Only enforces what is switched on. A switched-off option is left alone
/// rather than actively undone, so the app never reverts a setting the user made
/// by hand; releasing the fuse is an explicit step (`relax_global_identity`).
pub fn apply(
    settings: &GuardSettings,
    profiles: &[Profile],
    roots: &[RepoRoot],
    bindings: &[RepoBinding],
) -> Result<(), String> {
    if settings.unset_global_identity {
        git::unset_global_identity()?;
        git::set_use_config_only(true)?;
    }

    // The guard reads its allow-list through the includeIf region, so the
    // region is maintained whenever the guard is on, whatever the other switch
    // says.
    if settings.manage_gitconfig_includes || settings.guard_commits {
        write_includes(profiles, roots, bindings)?;
    } else {
        write_region("")?;
    }

    hooks::apply(settings.guard_commits)
}

/// Stops enforcing the fuse. The identity itself is not restored: the app cannot
/// know which one was there before, and inventing one is how this whole class of
/// mistake starts.
pub fn relax_global_identity() -> Result<(), String> {
    git::set_use_config_only(false)
}

fn write_includes(
    profiles: &[Profile],
    roots: &[RepoRoot],
    bindings: &[RepoBinding],
) -> Result<(), String> {
    let mut body = String::new();

    for profile in profiles {
        for platform in PLATFORMS {
            let Some(account) = profile.account(platform) else {
                continue;
            };
            let file = identity_file(profile, platform)?;
            fs::write(&file, identity_file_body(account)).map_err(|e| e.to_string())?;
        }
    }

    // Repository-scoped: the addresses this one repository accepts, extras
    // included. Files of bindings that no longer exist go first, or a released
    // repository would keep its allow-list.
    let dir = identities_dir()?;
    if let Ok(entries) = fs::read_dir(&dir) {
        for entry in entries.flatten() {
            let name = entry.file_name().to_string_lossy().to_string();
            if name.starts_with(BINDING_FILE_PREFIX) {
                let _ = fs::remove_file(entry.path());
            }
        }
    }
    for binding in bindings {
        let Some(profile) = profiles.iter().find(|p| p.id == binding.profile_id) else {
            continue;
        };
        let emails = allowed_emails(binding, profile);
        if emails.is_empty() {
            continue;
        }
        let file = binding_file(binding)?;
        fs::write(&file, allow_list_body(&emails)).map_err(|e| e.to_string())?;
        let repo = binding.path.replace('\\', "/");
        body.push_str(&format!(
            "[includeIf \"gitdir/i:{}/\"]\n\tpath = {}\n",
            repo.trim_end_matches('/'),
            posix(&file)
        ));
    }

    // Folder-scoped: understood by libgit2, so TortoiseGit sees it too.
    for root in roots {
        let Some(profile) = profiles.iter().find(|p| p.id == root.profile_id) else {
            continue;
        };
        if profile.account(root.platform).is_none() {
            continue;
        }
        let dir = root.path.replace('\\', "/");
        let dir = dir.trim_end_matches('/');
        body.push_str(&format!(
            "[includeIf \"gitdir/i:{}/\"]\n\tpath = {}\n",
            dir,
            posix(&identity_file(profile, root.platform)?)
        ));
    }

    // Remote-scoped: only modern Git CLI understands `hasconfig`, but it follows
    // the repository wherever it is cloned, which a folder rule cannot.
    for profile in profiles {
        for platform in PLATFORMS {
            let Some(account) = profile.account(platform) else {
                continue;
            };
            let host = platform.canonical_host();
            let path = posix(&identity_file(profile, platform)?);
            for pattern in [
                format!("git@{}:{}/**", host, account.username),
                format!("https://{}/{}/**", host, account.username),
                // `**` only crosses `/` when it follows one, so the namespace
                // needs its own `*` — `git@host:**` would never match.
                format!("git@{}:*/**", crate::repos::host_alias(platform, profile)),
            ] {
                body.push_str(&format!(
                    "[includeIf \"hasconfig:remote.*.url:{}\"]\n\tpath = {}\n",
                    pattern, path
                ));
            }
        }
    }

    write_region(&body)
}

/// Replaces the managed region in `~/.gitconfig`, appending it at the end so a
/// generated `[user]` include always wins over one written earlier in the file.
fn write_region(body: &str) -> Result<(), String> {
    let path = gitconfig_path()?;
    let existing = fs::read_to_string(&path).unwrap_or_default();

    // Nothing to write and nothing of ours to remove: leave the file untouched
    // rather than rewriting it on every profile switch.
    if body.trim().is_empty() && !existing.contains(MANAGED_HEADER) {
        return Ok(());
    }

    let mut result = strip_region(&existing).trim_end().to_string();

    if !body.trim().is_empty() {
        if !result.is_empty() {
            result.push_str("\n\n");
        }
        result.push_str(MANAGED_HEADER);
        result.push_str("\n\n");
        result.push_str(body.trim_end());
        result.push('\n');
        result.push_str(MANAGED_FOOTER);
    }

    if !result.is_empty() {
        result.push('\n');
    }

    if result == existing {
        return Ok(());
    }

    // One backup, taken the first time the app rewrites the file.
    if !existing.is_empty() {
        let backup = path.with_file_name(".gitconfig.gam-backup");
        if !backup.exists() {
            fs::write(&backup, &existing).map_err(|e| e.to_string())?;
        }
    }

    fs::write(&path, result).map_err(|e| e.to_string())
}

fn strip_region(config: &str) -> String {
    let mut result = config.to_string();
    while let (Some(start), Some(end)) = (result.find(MANAGED_HEADER), result.find(MANAGED_FOOTER))
    {
        if start > end {
            break;
        }
        let after = result[end + MANAGED_FOOTER.len()..]
            .find('\n')
            .map(|n| end + MANAGED_FOOTER.len() + n + 1)
            .unwrap_or(result.len());
        result = format!("{}{}", &result[..start], &result[after..]);
    }
    result
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn strips_only_the_managed_region() {
        let config = format!(
            "[user]\n\tname = a\n\n{}\n\n[includeIf \"x\"]\n\tpath = y\n{}\n[core]\n\tx = 1\n",
            MANAGED_HEADER, MANAGED_FOOTER
        );
        let stripped = strip_region(&config);
        assert!(stripped.contains("[user]"));
        assert!(stripped.contains("[core]"));
        assert!(!stripped.contains("includeIf"));
        assert!(!stripped.contains(MANAGED_HEADER));
    }

    #[test]
    fn stripping_is_idempotent_without_a_region() {
        let config = "[user]\n\tname = a\n";
        assert_eq!(strip_region(config), config);
    }

    /// The allow-list file is what the global hook reads through `git config
    /// --get-all`, so git's own parser is the only judge of its shape. The
    /// account's address has to come out of the identity file for the same
    /// reason: a repository matched by remote alone is guarded through it.
    #[test]
    fn the_allow_list_reads_back_through_gits_own_parser() {
        let dir = std::env::temp_dir().join(format!("gam-allow-{}", std::process::id()));
        let _ = fs::remove_dir_all(&dir);
        fs::create_dir_all(&dir).unwrap();

        let list = dir.join("binding.gitconfig");
        fs::write(
            &list,
            allow_list_body(&["a@example.com".to_string(), "bot@example.com".to_string()]),
        )
        .unwrap();
        let read = |file: &std::path::Path| {
            let out = std::process::Command::new("git")
                .args(["config", "-f"])
                .arg(file)
                .args(["--get-all", "gam.allowedEmail"])
                .output()
                .expect("git must be on PATH");
            String::from_utf8_lossy(&out.stdout).trim().to_string()
        };
        assert_eq!(
            read(&list),
            "a@example.com
bot@example.com"
        );

        let identity = dir.join("identity.gitconfig");
        fs::write(&identity, identity_file_body(&signing_account(false))).unwrap();
        assert_eq!(read(&identity), signing_account(false).git_email);

        let _ = fs::remove_dir_all(&dir);
    }

    /// The generated identity file is written by hand and read by git, so the
    /// only check that means anything is git's own parser reading back exactly
    /// what went in. A name carrying a backslash or a quote is ordinary —
    /// a Windows path pasted into a display name, a nickname in quotes — and
    /// writing it unescaped produced a value git read differently, or a file it
    /// refused, which silently left the repository on the wrong identity.
    #[test]
    fn a_generated_identity_survives_gits_own_parser() {
        let dir = std::env::temp_dir().join(format!("gam-cfgval-{}", std::process::id()));
        let _ = fs::remove_dir_all(&dir);
        fs::create_dir_all(&dir).unwrap();

        let awkward = [
            // Escaping alone is what these need: unquoted, git swallowed the
            // quote characters and read back "Ann The Dev Smith".
            r#"Ann "The Dev" Smith"#,
            r"C:\Users\ann",
            r#"trailing backslash \"#,
            // These need the surrounding quotes: git trims whitespace around an
            // unquoted value, and a `#` starts a comment.
            "  padded  ",
            "Ann # 2",
            "plain name",
            "Работа",
        ];

        for (i, name) in awkward.iter().enumerate() {
            let file = dir.join(format!("{}.gitconfig", i));
            fs::write(&file, format!("[user]\n\tname = {}\n", config_value(name))).unwrap();

            let out = std::process::Command::new("git")
                .args(["config", "-f"])
                .arg(&file)
                .args(["--get", "user.name"])
                .output()
                .expect("git must be on PATH");
            assert!(
                out.status.success(),
                "git refused the file written for {:?}: {}",
                name,
                String::from_utf8_lossy(&out.stderr)
            );
            assert_eq!(
                String::from_utf8_lossy(&out.stdout).trim_end_matches(['\n', '\r']),
                *name,
                "git read back something other than what was written for {:?}",
                name
            );
        }

        // A newline would end the line and turn the rest into another key, so it
        // is dropped rather than written and misparsed.
        assert_eq!(config_value("a\nb"), "\"ab\"");

        let _ = fs::remove_dir_all(&dir);
    }

    fn signing_account(sign: bool) -> PlatformAccount {
        PlatformAccount {
            username: "octo".to_string(),
            git_name: "Octo".to_string(),
            git_email: "octo@example.com".to_string(),
            ssh_private_key_path: r"C:\Users\a\.ssh\id_ed25519".to_string(),
            ssh_public_key_path: r"C:\Users\a\.ssh\id_ed25519.pub".to_string(),
            sign_commits: sign,
            token: None,
        }
    }

    /// A signing block git cannot parse leaves every commit in the including
    /// repository failing, and the failure surfaces far from this file — so the
    /// values are read back with git's own parser rather than compared as text.
    /// The backslashes of a Windows key path are the part that breaks first.
    #[test]
    fn a_signing_identity_reads_back_as_git_sees_it() {
        let dir = std::env::temp_dir().join(format!("gam-signcfg-{}", std::process::id()));
        let _ = fs::remove_dir_all(&dir);
        fs::create_dir_all(&dir).unwrap();

        let read = |file: &std::path::Path, key: &str| -> String {
            let out = std::process::Command::new("git")
                .args(["config", "-f"])
                .arg(file)
                .args(["--get", key])
                .output()
                .expect("git must be on PATH");
            String::from_utf8_lossy(&out.stdout)
                .trim_end_matches(['\n', '\r'])
                .to_string()
        };

        let signing = dir.join("signing.gitconfig");
        fs::write(&signing, identity_file_body(&signing_account(true))).unwrap();
        assert_eq!(read(&signing, "user.email"), "octo@example.com");
        assert_eq!(read(&signing, "gpg.format"), "ssh");
        assert_eq!(
            read(&signing, "user.signingkey"),
            "C:/Users/a/.ssh/id_ed25519.pub"
        );
        assert_eq!(read(&signing, "commit.gpgsign"), "true");
        assert_eq!(read(&signing, "tag.gpgsign"), "true");

        // Off means absent, not `false`: an account that does not sign must not
        // override a repository that configured signing for itself.
        let plain = dir.join("plain.gitconfig");
        fs::write(&plain, identity_file_body(&signing_account(false))).unwrap();
        assert_eq!(read(&plain, "user.email"), "octo@example.com");
        assert_eq!(read(&plain, "commit.gpgsign"), "");
        assert_eq!(read(&plain, "user.signingkey"), "");

        let _ = fs::remove_dir_all(&dir);
    }
}
