//! Machine-wide guard rails.
//!
//! Two things live here. First, turning the global identity from a value into a
//! fuse: with no global `user.email` and `user.useConfigOnly` set, a repository
//! that was never bound refuses to commit instead of borrowing the identity of
//! whichever profile happens to be active. Second, a generated `includeIf`
//! region in `~/.gitconfig` so a fresh clone under a known root already knows
//! who it belongs to.
//!
//! The region is delimited the same way the SSH config region is, and anything
//! outside it is preserved byte for byte.

use crate::git;
use crate::models::{GuardSettings, Profile, RepoRoot};
use serde::{Deserialize, Serialize};
use std::fs;
use std::path::PathBuf;

const MANAGED_HEADER: &str = "# === begin git-account-manager ===";
const MANAGED_FOOTER: &str = "# === end git-account-manager ===";
const PLATFORMS: [&str; 3] = ["github", "gitlab", "bitbucket"];

fn gitconfig_path() -> Result<PathBuf, String> {
    Ok(dirs::home_dir()
        .ok_or("Cannot find home directory")?
        .join(".gitconfig"))
}

fn identities_dir() -> Result<PathBuf, String> {
    let dir = dirs::data_dir()
        .ok_or("Cannot find data directory")?
        .join("git-account-manager")
        .join("identities");
    fs::create_dir_all(&dir).map_err(|e| e.to_string())?;
    Ok(dir)
}

fn identity_file(profile: &Profile, platform: &str) -> Result<PathBuf, String> {
    Ok(identities_dir()?.join(format!("{}-{}.gitconfig", profile.slug(), platform)))
}

fn posix(path: &std::path::Path) -> String {
    path.to_string_lossy().replace('\\', "/")
}

// ---- Global identity fuse ----

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GuardStatus {
    pub global_name: String,
    pub global_email: String,
    pub use_config_only: bool,
    pub includes_managed: bool,
    pub gitconfig_path: String,
    pub ok: bool,
}

pub fn status(settings: &GuardSettings) -> GuardStatus {
    let identity = git::get_global_identity().unwrap_or(git::GitIdentity {
        name: String::new(),
        email: String::new(),
    });
    let use_config_only = git::get_global_config("user.useConfigOnly")
        .map(|v| v == "true")
        .unwrap_or(false);
    let path = gitconfig_path().unwrap_or_default();
    let includes_managed = fs::read_to_string(&path)
        .map(|c| c.contains(MANAGED_HEADER))
        .unwrap_or(false);

    let identity_ok =
        !settings.unset_global_identity || (identity.email.is_empty() && use_config_only);
    let includes_ok = !settings.manage_gitconfig_includes || includes_managed;

    GuardStatus {
        global_name: identity.name,
        global_email: identity.email,
        use_config_only,
        includes_managed,
        gitconfig_path: posix(&path),
        ok: identity_ok && includes_ok,
    }
}

/// Brings the machine in line with the settings.
///
/// Only enforces what is switched on. A switched-off option is left alone
/// rather than actively undone, so the app never reverts a setting the user made
/// by hand; releasing the fuse is an explicit step (`relax_global_identity`).
pub fn apply(
    settings: &GuardSettings,
    profiles: &[Profile],
    roots: &[RepoRoot],
) -> Result<(), String> {
    if settings.unset_global_identity {
        git::unset_global_identity()?;
        git::set_use_config_only(true)?;
    }

    if settings.manage_gitconfig_includes {
        write_includes(profiles, roots)
    } else {
        write_region("")
    }
}

/// Stops enforcing the fuse. The identity itself is not restored: the app cannot
/// know which one was there before, and inventing one is how this whole class of
/// mistake starts.
pub fn relax_global_identity() -> Result<(), String> {
    git::set_use_config_only(false)
}

// ---- Generated includeIf region ----

fn write_includes(profiles: &[Profile], roots: &[RepoRoot]) -> Result<(), String> {
    let mut body = String::new();

    for profile in profiles {
        for platform in PLATFORMS {
            let Some(account) = profile.account(platform) else {
                continue;
            };
            let file = identity_file(profile, platform)?;
            fs::write(
                &file,
                format!(
                    "# Generated by git-account-manager. Edits are overwritten.\n[user]\n\tname = {}\n\temail = {}\n",
                    account.git_name, account.git_email
                ),
            )
            .map_err(|e| e.to_string())?;
        }
    }

    // Folder-scoped: understood by libgit2, so TortoiseGit sees it too.
    for root in roots {
        let Some(profile) = profiles.iter().find(|p| p.id == root.profile_id) else {
            continue;
        };
        if profile.account(&root.platform).is_none() {
            continue;
        }
        let dir = root.path.replace('\\', "/");
        let dir = dir.trim_end_matches('/');
        body.push_str(&format!(
            "[includeIf \"gitdir/i:{}/\"]\n\tpath = {}\n",
            dir,
            posix(&identity_file(profile, &root.platform)?)
        ));
    }

    // Remote-scoped: only modern Git CLI understands `hasconfig`, but it follows
    // the repository wherever it is cloned, which a folder rule cannot.
    for profile in profiles {
        for platform in PLATFORMS {
            let Some(account) = profile.account(platform) else {
                continue;
            };
            let host = crate::repos::canonical_host(platform);
            let path = posix(&identity_file(profile, platform)?);
            for pattern in [
                format!("git@{}:{}/**", host, account.username),
                format!("https://{}/{}/**", host, account.username),
                // `**` only crosses `/` when it follows one, so the namespace
                // needs its own `*` — `git@host:**` would never match.
                format!("git@{}-{}:*/**", platform, profile.slug()),
            ] {
                body.push_str(&format!(
                    "[includeIf \"hasconfig:remote.*.url:{}\"]\n\tpath = {}\n",
                    pattern, path
                ));
            }
        }
    }

    write_region(&body)
}

/// Replaces the managed region in `~/.gitconfig`, appending it at the end so a
/// generated `[user]` include always wins over one written earlier in the file.
fn write_region(body: &str) -> Result<(), String> {
    let path = gitconfig_path()?;
    let existing = fs::read_to_string(&path).unwrap_or_default();

    // Nothing to write and nothing of ours to remove: leave the file untouched
    // rather than rewriting it on every profile switch.
    if body.trim().is_empty() && !existing.contains(MANAGED_HEADER) {
        return Ok(());
    }

    let mut result = strip_region(&existing).trim_end().to_string();

    if !body.trim().is_empty() {
        if !result.is_empty() {
            result.push_str("\n\n");
        }
        result.push_str(MANAGED_HEADER);
        result.push_str("\n\n");
        result.push_str(body.trim_end());
        result.push('\n');
        result.push_str(MANAGED_FOOTER);
    }

    if !result.is_empty() {
        result.push('\n');
    }

    if result == existing {
        return Ok(());
    }

    // One backup, taken the first time the app rewrites the file.
    if !existing.is_empty() {
        let backup = path.with_file_name(".gitconfig.gam-backup");
        if !backup.exists() {
            fs::write(&backup, &existing).map_err(|e| e.to_string())?;
        }
    }

    fs::write(&path, result).map_err(|e| e.to_string())
}

fn strip_region(config: &str) -> String {
    let mut result = config.to_string();
    while let (Some(start), Some(end)) = (result.find(MANAGED_HEADER), result.find(MANAGED_FOOTER))
    {
        if start > end {
            break;
        }
        let after = result[end + MANAGED_FOOTER.len()..]
            .find('\n')
            .map(|n| end + MANAGED_FOOTER.len() + n + 1)
            .unwrap_or(result.len());
        result = format!("{}{}", &result[..start], &result[after..]);
    }
    result
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn strips_only_the_managed_region() {
        let config = format!(
            "[user]\n\tname = a\n\n{}\n\n[includeIf \"x\"]\n\tpath = y\n{}\n[core]\n\tx = 1\n",
            MANAGED_HEADER, MANAGED_FOOTER
        );
        let stripped = strip_region(&config);
        assert!(stripped.contains("[user]"));
        assert!(stripped.contains("[core]"));
        assert!(!stripped.contains("includeIf"));
        assert!(!stripped.contains(MANAGED_HEADER));
    }

    #[test]
    fn stripping_is_idempotent_without_a_region() {
        let config = "[user]\n\tname = a\n";
        assert_eq!(strip_region(config), config);
    }
}
