//! The folder rules: what turns a directory into one account's territory.
//!
//! Everything a repository needs is written outside it. One generated
//! `includeIf "gitdir:"` block per watched folder points at a file holding the
//! identity, the SSH key to reach the host with, and the address the commit
//! guard accepts. Git applies it to every repository under the folder at any
//! depth, including one cloned there after the rule was written, and nothing of
//! this app's ever lands inside a repository.
//!
//! The region is delimited the same way the SSH config region is, and anything
//! outside it is preserved byte for byte.

use crate::git;
use crate::hooks;
use crate::models::{
    GuardSettings, Platform, PlatformAccount, Profile, RepoRoot, MANAGED_FOOTER, MANAGED_HEADER,
    PLATFORMS,
};
use serde::{Deserialize, Serialize};
use std::fs;
use std::path::PathBuf;

fn gitconfig_path() -> Result<PathBuf, String> {
    Ok(dirs::home_dir()
        .ok_or("Cannot find home directory")?
        .join(".gitconfig"))
}

pub fn identities_dir() -> Result<PathBuf, String> {
    let dir = dirs::data_dir()
        .ok_or("Cannot find data directory")?
        .join("git-account-manager")
        .join("identities");
    fs::create_dir_all(&dir).map_err(|e| e.to_string())?;
    Ok(dir)
}

pub fn identity_file(profile: &Profile, platform: Platform) -> Result<PathBuf, String> {
    Ok(identities_dir()?.join(format!(
        "{}-{}.gitconfig",
        profile.slug(),
        platform.as_str()
    )))
}

fn posix(path: &std::path::Path) -> String {
    path.to_string_lossy().replace('\\', "/")
}

/// Quotes a value the way git's own parser reads it back, so a Windows path's
/// backslashes survive and a stray newline cannot start a second key.
fn config_value(raw: &str) -> String {
    let mut out = String::with_capacity(raw.len() + 2);
    out.push('"');
    for c in raw.chars() {
        match c {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' | '\r' => {}
            _ => out.push(c),
        }
    }
    out.push('"');
    out
}

/// The whole content of one generated identity file: who the account is, which
/// key signs and which key reaches the host, and the address the commit guard
/// accepts here.
///
/// `gpg.format = ssh` has to travel with `user.signingkey`, or git reads the
/// path as a GPG key id and every commit in the including repository fails.
fn identity_file_body(account: &PlatformAccount, ssh_program: &str) -> String {
    let mut body = String::from("# Generated by git-account-manager. Edits are overwritten.\n");
    body.push_str(&format!(
        "[user]\n\tname = {}\n\temail = {}\n",
        config_value(&account.git_name),
        config_value(&account.git_email)
    ));
    if let Some(key) = account.signing_key() {
        body.push_str(&format!(
            "\tsigningkey = {}\n[gpg]\n\tformat = ssh\n[commit]\n\tgpgsign = true\n[tag]\n\tgpgsign = true\n",
            config_value(&key.replace('\\', "/"))
        ));
    }
    // The key follows the folder, so a repository under it reaches the host as
    // this account whichever profile is active and whatever `origin` says.
    // `IdentitiesOnly` stops ssh from offering the agent's other keys, which is
    // how the wrong account answers on a host both profiles can reach.
    let private = account.ssh_private_key_path.trim();
    if !private.is_empty() {
        body.push_str(&format!(
            "[core]\n\tsshCommand = {}\n",
            config_value(&format!(
                "{} -i \"{}\" -o IdentitiesOnly=yes",
                ssh_program,
                private.replace('\\', "/")
            ))
        ));
    }
    body.push_str(&format!(
        "[gam]\n\tallowedEmail = {}\n",
        config_value(&account.git_email)
    ));
    body
}

/// Whose key answers on a bare SSH host; `profile` is `None` where none does.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SshHostOwner {
    pub host: String,
    pub profile: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GuardStatus {
    pub global_name: String,
    pub global_email: String,
    pub gitconfig_path: String,
    /// The generated region is in `~/.gitconfig`.
    pub rules_written: bool,
    pub ssh_hosts: Vec<SshHostOwner>,
    /// What the global `core.hooksPath` points at, if anything.
    pub hooks_path: Option<String>,
    /// `global` when the dispatchers are in force, `foreign` when the path is
    /// somebody else's, `off` when nothing is set.
    pub hooks: String,
    /// `user.useConfigOnly` is set, so git refuses to invent an identity.
    pub use_config_only: bool,
    pub ok: bool,
}

pub fn status(settings: &GuardSettings, profiles: &[Profile], roots: &[RepoRoot]) -> GuardStatus {
    let identity = git::get_global_identity().unwrap_or(git::GitIdentity {
        name: String::new(),
        email: String::new(),
    });
    let use_config_only = git::get_global_config("user.useConfigOnly")
        .map(|v| v == "true")
        .unwrap_or(false);
    let path = gitconfig_path().unwrap_or_default();
    let rules_written = fs::read_to_string(&path)
        .map(|c| c.contains(MANAGED_HEADER))
        .unwrap_or(false);

    let hooks_status = hooks::status();
    let hooks_state = match (&hooks_status.hooks_path, hooks_status.ours) {
        (Some(_), true) => "global",
        (Some(_), false) => "foreign",
        (None, _) => "off",
    };
    let hooks_ok = !settings.guard_commits || hooks_state == "global";
    let rules_ok = roots.is_empty() || rules_written;
    let identity_ok =
        !settings.unset_global_identity || (identity.email.is_empty() && use_config_only);

    GuardStatus {
        global_name: identity.name,
        global_email: identity.email,
        gitconfig_path: posix(&path),
        rules_written,
        use_config_only,
        ssh_hosts: crate::ssh::bare_host_owners(profiles)
            .into_iter()
            .map(|(platform, owner)| SshHostOwner {
                host: platform.canonical_host().to_string(),
                profile: owner.map(|p| p.name.clone()),
            })
            .collect(),
        hooks_path: hooks_status.hooks_path,
        hooks: hooks_state.to_string(),
        ok: hooks_ok && rules_ok && identity_ok,
    }
}

/// Brings the machine in line with the stored folders: the identity files, the
/// region that points at them, and the hook dispatchers that read the allow-list
/// out of them.
pub fn apply(
    settings: &GuardSettings,
    profiles: &[Profile],
    roots: &[RepoRoot],
) -> Result<(), String> {
    if settings.unset_global_identity {
        git::unset_global_identity()?;
        git::set_use_config_only(true)?;
    }
    write_rules(profiles, roots)?;
    hooks::apply(settings.guard_commits)
}

/// Which profile supplies the machine's default identity, for everything no
/// folder rule claims.
///
/// `None` with the fuse armed: no global `user.name`/`user.email` and
/// `user.useConfigOnly` set means git refuses to commit outside a claimed
/// folder rather than signing the work with whoever is active.
pub fn machine_default<'a>(
    settings: &GuardSettings,
    profiles: &'a [Profile],
) -> Option<&'a Profile> {
    if settings.unset_global_identity {
        return None;
    }
    profiles.iter().find(|p| p.is_active)
}

/// Stops enforcing the fuse. The identity itself is not restored here: the
/// active profile's is written by the next sync.
pub fn relax_global_identity() -> Result<(), String> {
    git::set_use_config_only(false)
}

/// Folders inside another folder come last, because git applies the includes in
/// order and the last `user.email` read is the one that counts. A nested folder
/// belonging to another profile only wins that way, and storage order is not it.
fn by_depth_then_path(roots: &[RepoRoot]) -> Vec<&RepoRoot> {
    let depth = |r: &RepoRoot| {
        r.path
            .replace('\\', "/")
            .trim_end_matches('/')
            .matches('/')
            .count()
    };
    let mut ordered: Vec<&RepoRoot> = roots.iter().collect();
    ordered.sort_by(|a, b| depth(a).cmp(&depth(b)).then_with(|| a.path.cmp(&b.path)));
    ordered
}

/// `std::fs::canonicalize` answers with an extended-length path on Windows
/// (`\\?\C:\...`), a form git's `gitdir` matcher does not recognise.
fn without_extended_prefix(path: &std::path::Path) -> String {
    let text = path.to_string_lossy().replace('\\', "/");
    match text.strip_prefix("//?/UNC/") {
        Some(share) => format!("//{}", share),
        None => text.strip_prefix("//?/").unwrap_or(&text).to_string(),
    }
}

/// One spelling for a folder wherever it came from: a file picker, a stored
/// state file or a relink.
///
/// Git matches a `gitdir` pattern against the path it resolves a repository to,
/// with 8.3 short names expanded and junctions and symlinks followed, so a rule
/// written against any other spelling of the same folder matches nothing and
/// says nothing about why. The folder is asked what it really is rather than
/// trusted to have arrived in that form. A path that is not there keeps the
/// spelling it came with, which is what the doctor reports as missing.
/// The trailing slash is trimmed from the answer rather than from the question:
/// on Windows `canonicalize("D:")` resolves to the current directory on that
/// drive, so trimming first would turn a whole drive into whatever folder the
/// process happened to be in.
pub fn normalize_folder(path: &str) -> String {
    let given = path.replace('\\', "/");
    let real = std::fs::canonicalize(&given)
        .map(|real| without_extended_prefix(&real))
        .unwrap_or(given);
    real.trim_end_matches('/').to_string()
}

/// `gitdir/i:` needs a trailing slash to reach everything underneath, and the
/// case-insensitive form because Windows hands the same folder back with either
/// drive-letter case.
pub fn gitdir_pattern(path: &str) -> String {
    format!("{}/", normalize_folder(path))
}

fn write_rules(profiles: &[Profile], roots: &[RepoRoot]) -> Result<(), String> {
    let ssh = crate::openssh_integration::ssh_program();
    let mut used: Vec<PathBuf> = Vec::new();

    for profile in profiles {
        for platform in PLATFORMS {
            let Some(account) = profile.account(platform) else {
                continue;
            };
            let file = identity_file(profile, platform)?;
            fs::write(&file, identity_file_body(account, &ssh)).map_err(|e| e.to_string())?;
            used.push(file);
        }
    }

    // A deleted profile or a disconnected platform leaves a file no rule points
    // at any more; a later profile of the same name would otherwise inherit an
    // identity nobody wrote for it.
    if let Ok(entries) = fs::read_dir(identities_dir()?) {
        for entry in entries.flatten() {
            let path = entry.path();
            let is_ours = path
                .extension()
                .is_some_and(|e| e.eq_ignore_ascii_case("gitconfig"));
            if is_ours && !used.iter().any(|u| u == &path) {
                let _ = fs::remove_file(path);
            }
        }
    }

    write_region(&rules_body(profiles, roots)?)
}

/// Every folder's include line, in the order git has to read them.
///
/// The doctor decides whether a folder still has its rule by looking for
/// `rule_line` in the region, so the region is built out of the same function:
/// two spellings of one line would leave the doctor reporting a rule that is
/// right there.
fn rules_body(profiles: &[Profile], roots: &[RepoRoot]) -> Result<String, String> {
    let mut body = String::new();
    for root in by_depth_then_path(roots) {
        let Some(profile) = profiles.iter().find(|p| p.id == root.profile_id) else {
            continue;
        };
        if profile.account(root.platform).is_none() {
            continue;
        }
        body.push_str(&rule_line(root, profile)?);
    }
    Ok(body)
}

/// The one include line a folder is supposed to have. The doctor compares the
/// region against this rather than parsing it back, so pattern and target are
/// checked by the same code that writes them.
pub fn rule_line(root: &RepoRoot, profile: &Profile) -> Result<String, String> {
    Ok(format!(
        "[includeIf \"gitdir/i:{}\"]
	path = {}
",
        gitdir_pattern(&root.path),
        config_value(&posix(&identity_file(profile, root.platform)?))
    ))
}

/// The generated region of `~/.gitconfig`, empty when there is none.
pub fn region_text() -> String {
    let Ok(path) = gitconfig_path() else {
        return String::new();
    };
    let Ok(existing) = fs::read_to_string(path) else {
        return String::new();
    };
    let (Some(start), Some(end)) = (existing.find(MANAGED_HEADER), existing.find(MANAGED_FOOTER))
    else {
        return String::new();
    };
    if start > end {
        return String::new();
    }
    existing[start..end].to_string()
}

/// Replaces the managed region in `~/.gitconfig`, appending it at the end so a
/// generated `[user]` include always wins over one written earlier in the file.
fn write_region(body: &str) -> Result<(), String> {
    let path = gitconfig_path()?;
    let existing = fs::read_to_string(&path).unwrap_or_default();

    // Nothing to write and nothing of ours to remove: leave the file untouched
    // rather than rewriting it on every profile switch.
    if body.trim().is_empty() && !existing.contains(MANAGED_HEADER) {
        return Ok(());
    }

    let mut result = strip_region(&existing).trim_end().to_string();

    if !body.trim().is_empty() {
        if !result.is_empty() {
            result.push_str("\n\n");
        }
        result.push_str(MANAGED_HEADER);
        result.push_str("\n\n");
        result.push_str(body.trim_end());
        result.push('\n');
        result.push_str(MANAGED_FOOTER);
    }

    if !result.is_empty() {
        result.push('\n');
    }

    if result == existing {
        return Ok(());
    }

    // One backup, taken the first time the app rewrites the file.
    if !existing.is_empty() {
        let backup = path.with_file_name(".gitconfig.gam-backup");
        if !backup.exists() {
            fs::write(&backup, &existing).map_err(|e| e.to_string())?;
        }
    }

    fs::write(&path, result).map_err(|e| e.to_string())
}

fn strip_region(config: &str) -> String {
    let mut result = config.to_string();
    while let (Some(start), Some(end)) = (result.find(MANAGED_HEADER), result.find(MANAGED_FOOTER))
    {
        if start > end {
            break;
        }
        let after = result[end + MANAGED_FOOTER.len()..]
            .find('\n')
            .map(|n| end + MANAGED_FOOTER.len() + n + 1)
            .unwrap_or(result.len());
        result = format!("{}{}", &result[..start], &result[after..]);
    }
    result
}

#[cfg(test)]
mod tests {
    use super::*;

    fn account(sign: bool) -> PlatformAccount {
        PlatformAccount {
            username: "octo".to_string(),
            git_name: "Octo".to_string(),
            git_email: "octo@example.com".to_string(),
            ssh_private_key_path: r"C:\Users\a\.ssh\id_ed25519".to_string(),
            ssh_public_key_path: r"C:\Users\a\.ssh\id_ed25519.pub".to_string(),
            sign_commits: sign,
            token: None,
        }
    }

    fn root_at(path: &str) -> RepoRoot {
        RepoRoot {
            path: path.to_string(),
            profile_id: "p1".to_string(),
            platform: Platform::Github,
            fingerprint: vec![],
        }
    }

    fn read(file: &std::path::Path, key: &str) -> String {
        let out = std::process::Command::new("git")
            .args(["config", "-f"])
            .arg(file)
            .args(["--get", key])
            .output()
            .expect("git must be on PATH");
        String::from_utf8_lossy(&out.stdout)
            .trim_end_matches(['\n', '\r'])
            .to_string()
    }

    #[test]
    fn strips_only_the_managed_region() {
        let config = format!(
            "[user]\n\tname = a\n\n{}\n\n[includeIf \"x\"]\n\tpath = y\n{}\n[core]\n\tx = 1\n",
            MANAGED_HEADER, MANAGED_FOOTER
        );
        let stripped = strip_region(&config);
        assert!(stripped.contains("[user]"));
        assert!(stripped.contains("[core]"));
        assert!(!stripped.contains("includeIf"));
        assert!(!stripped.contains(MANAGED_HEADER));
    }

    #[test]
    fn stripping_is_idempotent_without_a_region() {
        let config = "[user]\n\tname = a\n";
        assert_eq!(strip_region(config), config);
    }

    /// Everything a folder rule delivers lives in this one file, and a block git
    /// cannot parse leaves every commit under the folder failing far from here —
    /// so the values are read back with git's own parser rather than compared as
    /// text. The backslashes of a Windows key path break first.
    #[test]
    fn the_identity_file_reads_back_as_git_sees_it() {
        let dir = std::env::temp_dir().join(format!("gam-identity-{}", std::process::id()));
        let _ = fs::remove_dir_all(&dir);
        fs::create_dir_all(&dir).unwrap();

        let signing = dir.join("signing.gitconfig");
        fs::write(&signing, identity_file_body(&account(true), "ssh")).unwrap();
        assert_eq!(read(&signing, "user.name"), "Octo");
        assert_eq!(read(&signing, "user.email"), "octo@example.com");
        assert_eq!(read(&signing, "gpg.format"), "ssh");
        assert_eq!(
            read(&signing, "user.signingkey"),
            "C:/Users/a/.ssh/id_ed25519.pub"
        );
        assert_eq!(read(&signing, "commit.gpgsign"), "true");
        assert_eq!(read(&signing, "tag.gpgsign"), "true");
        // What carries the key to the host, quoted so a path with a space in it
        // still reaches ssh as one argument.
        assert_eq!(
            read(&signing, "core.sshCommand"),
            "ssh -i \"C:/Users/a/.ssh/id_ed25519\" -o IdentitiesOnly=yes"
        );
        // What the commit guard reads.
        assert_eq!(read(&signing, "gam.allowedEmail"), "octo@example.com");

        // Off means absent, not `false`: an account that does not sign must not
        // override a repository that configured signing for itself.
        let plain = dir.join("plain.gitconfig");
        fs::write(&plain, identity_file_body(&account(false), "ssh")).unwrap();
        assert_eq!(read(&plain, "user.email"), "octo@example.com");
        assert_eq!(read(&plain, "commit.gpgsign"), "");
        assert_eq!(read(&plain, "user.signingkey"), "");

        // A newline would end the line and turn the rest into another key, so it
        // is dropped rather than written and misparsed.
        assert_eq!(config_value("a\nb"), "\"ab\"");

        let _ = fs::remove_dir_all(&dir);
    }

    /// An account with no key must not claim one: a `core.sshCommand` naming an
    /// empty `-i` fails every fetch under the folder.
    #[test]
    fn an_account_without_a_key_configures_no_ssh_command() {
        let mut acc = account(false);
        acc.ssh_private_key_path = String::new();
        assert!(!identity_file_body(&acc, "ssh").contains("sshCommand"));
    }

    #[test]
    fn a_nested_folder_is_written_after_the_folder_it_sits_in() {
        let roots = vec![
            root_at("D:/repos/work/team/inner"),
            root_at("D:/repos"),
            root_at("D:/repos/work"),
        ];
        let ordered: Vec<&str> = by_depth_then_path(&roots)
            .iter()
            .map(|r| r.path.as_str())
            .collect();
        assert_eq!(
            ordered,
            vec!["D:/repos", "D:/repos/work", "D:/repos/work/team/inner"]
        );
    }

    /// A rule is only worth writing against the path git will resolve the
    /// repository to. The spelling the folder arrived in is not that path
    /// whenever a short name, a junction or a `..` stands between them, and a
    /// rule built from it matches nothing without saying so.
    #[test]
    fn a_folder_is_named_by_what_the_filesystem_says_it_is() {
        let dir = std::env::temp_dir().join(format!("gam-normalize-{}", std::process::id()));
        let _ = fs::remove_dir_all(&dir);
        fs::create_dir_all(dir.join("work")).unwrap();

        let direct = normalize_folder(&posix(&dir.join("work")));
        let detour = normalize_folder(&posix(&dir.join("work").join("..").join("work")));
        assert_eq!(direct, detour, "one folder, one spelling");
        assert!(direct.ends_with("/work"), "{}", direct);

        // Windows answers a canonicalize with an extended-length path, which
        // git's matcher treats as a name rather than a location.
        assert!(!direct.contains("//?/"), "{}", direct);
        assert!(!direct.contains('\\'), "{}", direct);

        // A trailing slash is one more spelling of the same folder.
        assert_eq!(normalize_folder(&format!("{}/", direct)), direct);

        // A folder that is not there is still the folder the doctor reports as
        // missing, so it keeps the spelling it was stored with.
        let gone = posix(&dir.join("never-created"));
        assert_eq!(normalize_folder(&gone), gone);

        // Windows reads a bare drive letter as the current directory on that
        // drive, so a whole drive claimed as a folder must not come back as
        // whatever directory this process happens to sit in.
        #[cfg(windows)]
        {
            let root = posix(&dir).chars().take(2).collect::<String>();
            assert_eq!(normalize_folder(&format!("{}/", root)), root);
        }

        let _ = fs::remove_dir_all(&dir);
    }

    /// The pattern has to reach a repository's `.git` directory at any depth,
    /// and a folder handed back by the file picker may carry a trailing slash
    /// or backslashes.
    #[test]
    fn the_folder_pattern_ends_in_one_slash_whatever_the_path_looked_like() {
        assert_eq!(gitdir_pattern("D:/repos/work"), "D:/repos/work/");
        assert_eq!(gitdir_pattern("D:/repos/work/"), "D:/repos/work/");
        assert_eq!(gitdir_pattern(r"D:\repos\work"), "D:/repos/work/");
    }

    fn profile_named(id: &str) -> Profile {
        Profile {
            id: id.to_string(),
            name: id.to_string(),
            default_platform: None,
            github: Some(account(false)),
            gitlab: None,
            bitbucket: None,
            is_active: false,
        }
    }

    /// What the doctor looks for has to be what was written, and a folder whose
    /// profile or account is gone must leave no rule pointing at an identity
    /// file nobody maintains.
    #[test]
    fn the_region_holds_one_rule_per_folder_in_the_order_git_reads_them() {
        let mut inner = root_at("D:/repos/work/inner");
        inner.profile_id = "second".to_string();
        let mut orphan = root_at("D:/repos/gone");
        orphan.profile_id = "deleted".to_string();
        let roots = vec![inner, orphan, root_at("D:/repos/work")];

        let profiles = vec![profile_named("p1"), profile_named("second")];
        let body = rules_body(&profiles, &roots).unwrap();

        let outer = rule_line(&roots[2], &profiles[0]).unwrap();
        let nested = rule_line(&roots[0], &profiles[1]).unwrap();
        assert_eq!(body, format!("{}{}", outer, nested));
        assert!(
            !body.contains("D:/repos/gone"),
            "a folder whose profile is gone must not keep a rule: {}",
            body
        );
    }

    /// The fuse is what stops an unclaimed repository from borrowing the active
    /// profile, so what it does is decide whether the machine has a default
    /// identity to write at all.
    #[test]
    fn the_fuse_leaves_the_machine_without_a_default_identity() {
        let mut active = profile_named("work");
        active.is_active = true;
        let profiles = vec![profile_named("home"), active];

        let mut settings = GuardSettings::default();
        assert_eq!(
            machine_default(&settings, &profiles).map(|p| p.name.as_str()),
            Some("work")
        );

        settings.unset_global_identity = true;
        assert!(machine_default(&settings, &profiles).is_none());
    }

    /// The whole model rests on git applying one folder rule to a repository
    /// several levels down, so it is asked rather than assumed.
    #[test]
    fn git_applies_the_generated_rule_to_a_repository_deep_under_the_folder() {
        let dir = std::env::temp_dir().join(format!("gam-rule-{}", std::process::id()));
        let _ = fs::remove_dir_all(&dir);
        let repo = dir.join("nested").join("deep").join("demo");
        fs::create_dir_all(&repo).unwrap();
        let repo_path = posix(&repo);
        std::process::Command::new("git")
            .args(["init", "-q", &repo_path])
            .output()
            .expect("git must be on PATH");

        let identity = dir.join("identity.gitconfig");
        fs::write(&identity, identity_file_body(&account(false), "ssh")).unwrap();
        let config = dir.join("global.gitconfig");
        fs::write(
            &config,
            format!(
                "[includeIf \"gitdir/i:{}\"]\n\tpath = {}\n",
                gitdir_pattern(&posix(&dir)),
                config_value(&posix(&identity))
            ),
        )
        .unwrap();

        let resolved = |key: &str| {
            let out = std::process::Command::new("git")
                .args(["-C", &repo_path, "config", "--get", key])
                .env("GIT_CONFIG_GLOBAL", &config)
                .output()
                .unwrap();
            String::from_utf8_lossy(&out.stdout).trim().to_string()
        };
        assert_eq!(
            resolved("user.email"),
            "octo@example.com",
            "a repository three levels down must still get the folder's identity"
        );
        // The key travels the same way the identity does. Without this the
        // repository pushes with whichever key the active profile owns the bare
        // host with, which is the failure the folder rule exists to prevent.
        assert_eq!(
            resolved("core.sshCommand"),
            "ssh -i \"C:/Users/a/.ssh/id_ed25519\" -o IdentitiesOnly=yes"
        );
        // And so does the address the commit guard accepts here.
        assert_eq!(resolved("gam.allowedEmail"), "octo@example.com");

        let _ = fs::remove_dir_all(&dir);
    }

    /// A directory that reaches the same place under another name. Junctions
    /// need no privilege on Windows; a symlink is the equivalent elsewhere.
    /// A machine that allows neither says so rather than passing quietly.
    fn link_dir(target: &std::path::Path, link: &std::path::Path) -> bool {
        #[cfg(windows)]
        {
            std::process::Command::new("cmd")
                .args(["/C", "mklink", "/J"])
                .arg(link)
                .arg(target)
                .output()
                .map(|out| out.status.success())
                .unwrap_or(false)
        }
        #[cfg(not(windows))]
        {
            std::os::unix::fs::symlink(target, link).is_ok()
        }
    }

    /// The failure this normalization exists for, end to end. Git resolves a
    /// repository to the path the filesystem really keeps it at, so a rule
    /// written against another name for the same folder — a junction, a
    /// symlink, an 8.3 short name — matched nothing and said nothing about it.
    #[test]
    fn a_rule_for_a_folder_reached_under_another_name_still_applies() {
        let dir = std::env::temp_dir().join(format!("gam-linked-{}", std::process::id()));
        let _ = fs::remove_dir_all(&dir);
        let target = dir.join("target");
        let link = dir.join("link");
        fs::create_dir_all(target.join("demo")).unwrap();
        if !link_dir(&target, &link) {
            eprintln!("no directory link available here: a linked folder is not verified");
            let _ = fs::remove_dir_all(&dir);
            return;
        }
        std::process::Command::new("git")
            .args(["init", "-q", &posix(&target.join("demo"))])
            .output()
            .expect("git must be on PATH");

        // The rule names where the repository really is, not the name the
        // folder was added under.
        let pattern = gitdir_pattern(&posix(&link));
        assert!(pattern.contains("/target/"), "{}", pattern);

        let identity = dir.join("identity.gitconfig");
        fs::write(&identity, identity_file_body(&account(false), "ssh")).unwrap();
        let config = dir.join("global.gitconfig");
        fs::write(
            &config,
            format!(
                "[includeIf \"gitdir/i:{}\"]\n\tpath = {}\n",
                pattern,
                config_value(&posix(&identity))
            ),
        )
        .unwrap();

        let out = std::process::Command::new("git")
            .args([
                "-C",
                &posix(&link.join("demo")),
                "config",
                "--get",
                "user.email",
            ])
            .env("GIT_CONFIG_GLOBAL", &config)
            .output()
            .unwrap();
        assert_eq!(
            String::from_utf8_lossy(&out.stdout).trim(),
            "octo@example.com",
            "a folder added under one name must still hand out its identity"
        );

        let _ = fs::remove_dir(&link);
        let _ = fs::remove_dir_all(&dir);
    }

    /// The two halves meet here: the folder rule is the only thing that says
    /// which address is allowed, and the global hook is the only thing that
    /// reads it. Either one tested alone leaves the seam between them untested,
    /// and the seam is where a repository commits as the wrong person.
    #[test]
    fn the_folder_rule_is_what_the_global_hook_refuses_a_wrong_commit_by() {
        let Some(sh) = hooks::shell() else {
            eprintln!("no POSIX shell on PATH: the guard is not exercised here");
            return;
        };

        let dir = std::env::temp_dir().join(format!("gam-endtoend-{}", std::process::id()));
        let _ = fs::remove_dir_all(&dir);
        let repo = dir.join("team").join("demo");
        fs::create_dir_all(&repo).unwrap();
        let repo_path = posix(&repo);
        std::process::Command::new("git")
            .args(["init", "-q", &repo_path])
            .output()
            .expect("git must be on PATH");

        let identity = dir.join("identity.gitconfig");
        fs::write(&identity, identity_file_body(&account(false), "ssh")).unwrap();
        // The same line the region carries, pointed at the file this test
        // wrote rather than the one the real installation keeps.
        let config = dir.join("global.gitconfig");
        fs::write(
            &config,
            format!(
                "[includeIf \"gitdir/i:{}\"]\n\tpath = {}\n",
                gitdir_pattern(&posix(&dir)),
                config_value(&posix(&identity))
            ),
        )
        .unwrap();

        let hook_dir = dir.join("hooks");
        hooks::write_scripts(&hook_dir).unwrap();

        let commit_as = |email: &str| {
            std::process::Command::new("git")
                .args(["-C", &repo_path, "config", "--local", "user.email", email])
                .output()
                .unwrap();
            std::process::Command::new(sh)
                .arg(hook_dir.join("pre-commit"))
                .current_dir(&repo_path)
                .env("GIT_CONFIG_GLOBAL", &config)
                .env("GIT_AUTHOR_NAME", "Octo")
                .env("GIT_COMMITTER_NAME", "Octo")
                .output()
                .expect("the hook must start")
        };

        let refused = commit_as("stranger@example.com");
        let stderr = String::from_utf8_lossy(&refused.stderr).to_string();
        assert!(
            !refused.status.success(),
            "the folder's rule allows only its own account: {}",
            stderr
        );
        assert!(stderr.contains("stranger@example.com"), "{}", stderr);

        let accepted = commit_as("octo@example.com");
        assert!(
            accepted.status.success(),
            "the account the folder belongs to must commit: {}",
            String::from_utf8_lossy(&accepted.stderr)
        );

        let _ = fs::remove_dir_all(&dir);
    }
}
